package com.jfinal.base.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysRoleResource<M extends BaseSysRoleResource<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setRoleId(java.lang.Integer roleId) {
		set("role_id", roleId);
	}

	public java.lang.Integer getRoleId() {
		return get("role_id");
	}

	public void setResourceId(java.lang.Integer resourceId) {
		set("resource_id", resourceId);
	}

	public java.lang.Integer getResourceId() {
		return get("resource_id");
	}

	public void setResourceType(java.lang.Integer resourceType) {
		set("resource_type", resourceType);
	}

	public java.lang.Integer getResourceType() {
		return get("resource_type");
	}

}
