package com.jfinal.base.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysMenu<M extends BaseSysMenu<M>> extends Model<M> implements IBean {

	public void setMenuId(java.lang.Integer menuId) {
		set("menu_id", menuId);
	}

	public java.lang.Integer getMenuId() {
		return get("menu_id");
	}

	public void setMenuName(java.lang.String menuName) {
		set("menu_name", menuName);
	}

	public java.lang.String getMenuName() {
		return get("menu_name");
	}

	public void setMenuUrl(java.lang.String menuUrl) {
		set("menu_url", menuUrl);
	}

	public java.lang.String getMenuUrl() {
		return get("menu_url");
	}

	public void setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
	}

	public java.lang.Integer getParentId() {
		return get("parent_id");
	}

	public void setMenuOrder(java.lang.Integer menuOrder) {
		set("menu_order", menuOrder);
	}

	public java.lang.Integer getMenuOrder() {
		return get("menu_order");
	}

	public void setMenuIcon(java.lang.String menuIcon) {
		set("menu_icon", menuIcon);
	}

	public java.lang.String getMenuIcon() {
		return get("menu_icon");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

}
