package com.jfinal.base.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysButton<M extends BaseSysButton<M>> extends Model<M> implements IBean {

	public void setButtonId(java.lang.Integer buttonId) {
		set("button_id", buttonId);
	}

	public java.lang.Integer getButtonId() {
		return get("button_id");
	}

	public void setMenuId(java.lang.Integer menuId) {
		set("menu_id", menuId);
	}

	public java.lang.Integer getMenuId() {
		return get("menu_id");
	}

	public void setButtonName(java.lang.String buttonName) {
		set("button_name", buttonName);
	}

	public java.lang.String getButtonName() {
		return get("button_name");
	}

	public void setButtonUrl(java.lang.String buttonUrl) {
		set("button_url", buttonUrl);
	}

	public java.lang.String getButtonUrl() {
		return get("button_url");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

}
