package com.jfinal.base.common.model;

import com.jfinal.base.common.model.base.BaseSysButton;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysButton extends BaseSysButton<SysButton> {
	public static final SysButton dao = new SysButton();
}
