package com.jfinal.base.common.model;

import com.jfinal.base.common.model.base.BaseSysLog;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysLog extends BaseSysLog<SysLog> {
	public static final SysLog dao = new SysLog();
	public Page<SysLog> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from sys_log order by id desc");
	}
}
