package com.jfinal.base.common.model;

import com.jfinal.base.common.model.base.BaseSysMenu;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysMenu extends BaseSysMenu<SysMenu> {
	public static final SysMenu dao = new SysMenu();
	public Page<SysMenu> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from sys_menu order by menu_id asc");
	}
}
