package com.jfinal.base.common.model;

import com.jfinal.base.common.model.base.BaseSysRole;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRole extends BaseSysRole<SysRole> {
	public static final SysRole dao = new SysRole();
	public Page<SysRole> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from sys_role order by role_id asc");
	}
}
